server:
  port: 8004
  servlet:
    context-path: /rabbitmq-topic-consumer-ack

spring:
  application:
    name: rabbitmq-topic-consumer-ack #服务名称
  thymeleaf:
    # 关闭缓存，即时刷新，上线生产环境需改成true
    cache: false
  rabbitmq:
    host: 192.168.253.130
    port: 5672
    username: sxf
    password: 123456
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #手动确认
#        prefetch: 1 #限制每次发送一条数据。
#        concurrency: 3 #同一个队列启动几个消费者
#        max-concurrency: 3 #启动消费者最大数量
  resources:
    static-locations: classpath:static/,file:static/

#自定义交换器配置信息
mq:
  config:
    #设置交换器的名称
    exchange: log.topic
    #死信交换器名称
    dlxexchange: exchange-dlx
    queue:
      #队列的名称
      name:
        #死信队列名
        dlx: queue-dlx
        all: log.all
        info: log.info
        error: log.error
    #路由键
    routingkey:
      info: '*.log.info'
      error: '*.log.error'
      all: '*.log.*'
      #死信路由键
      dlx: routingKey_dlx