server:
  port: 8002
  servlet:
    context-path: /rabbitmq-topic-consumer

spring:
  application:
    name: rabbitmq-topic-consumer #服务名称

  rabbitmq:
    host: 192.168.253.130
    port: 5672
    username: sxf
    password: 123456
    listener:
      type: simple
      simple:
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 1 #同一个队列启动几个消费者
        max-concurrency: 10 #启动消费者最大数量
        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5
          stateless: true
          #时间策略乘数因子
          multiplier: 1.0
          initial-interval: 1000ms
          max-interval: 10000ms

#自定义交换器配置信息
mq:
  config:
    #设置交换器的名称
    exchange: log.topic
    queue:
      #队列的名称
      name:
        all: log.all
        info: log.info
        error: log.error
    #路由键
    routingkey:
      info: '*.log.info'
      error: '*.log.error'
      all: '*.log.*'
